Build: Use toolchain feature instead of source/targetCompatibility
More concise and fixes the FloatBuffer NoSuchMethodError [1] in SVGComponent.

[1]: https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/